// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPFGYahuqQmTyP_ay0QVu3QEoWDQJUHH0',
    appId: '1:602684976603:web:9f4ea31c3e4b377f404bfe',
    messagingSenderId: '602684976603',
    projectId: 'playdoodledash',
    authDomain: 'playdoodledash.firebaseapp.com',
    storageBucket: 'playdoodledash.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfsFL2umm5fLxrIGydZ-Kikkgs6SagQ5g',
    appId: '1:602684976603:android:a685fcd8e793e9cf404bfe',
    messagingSenderId: '602684976603',
    projectId: 'playdoodledash',
    storageBucket: 'playdoodledash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0bfQ6IIcPMV3Of3qteC27oXEe1Fk1fz4',
    appId: '1:602684976603:ios:2acb1e33799b3b7f404bfe',
    messagingSenderId: '602684976603',
    projectId: 'playdoodledash',
    storageBucket: 'playdoodledash.appspot.com',
    iosClientId: '602684976603-cm601615chtkvtrqf4jnstpo4fhlmr7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.doodleDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0bfQ6IIcPMV3Of3qteC27oXEe1Fk1fz4',
    appId: '1:602684976603:ios:2acb1e33799b3b7f404bfe',
    messagingSenderId: '602684976603',
    projectId: 'playdoodledash',
    storageBucket: 'playdoodledash.appspot.com',
    iosClientId: '602684976603-cm601615chtkvtrqf4jnstpo4fhlmr7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.doodleDash',
  );
}
